version: '3.1'

services:
  db:
    build: .
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 5060:8080
